### ISSUE TITLE
ISSUE: Loss of black text clarity in white-dominant images when scaling 2x, 3x, 4x

### ISSUE THREAD

**Issue by fusefib** [ImageProcessing-ElectronicPublications/scantailor-experimental#33] opened 2024-05-06 19:25 UTC
**Description:**
I am experiencing difficulties with the normal binarizing feature in ScanTailor-Experimental. When attempting to process an image containing predominantly white background with little black text, the resulting binarized image displays faint or erased text when scaling up the resolution to `2x` or higher. Adjusting the `Curve/Sqr color` settings from `0.5/0` to `1/1` provides some improvement but does not fully restore the text clarity. Changing the Threshold method from `Otsu` does, but keeping `Otsu` is preferred. Setting the thickness to the max doesn't help.

**Expected Behavior:**
The binarization process should maintain the clarity and legibility of the black text, even when scaling up the resolution.

**Actual Behavior:**
The black text becomes faint or disappears entirely in the binarized image when the resolution is increased.

**Environment:**
- ScanTailor-Experimental version: 0.2024.05.03-X86-64-Qt6 ("threshold" from Releases)
- Operating System: Windows 10

**Steps to reproduce:**
- Add attached image to a new project.
- Go directly to Stage 6 - `Output`.
- Check `Resolution Enhancement` box and click `2x`.
- 4x disappears most of the black.

**Notes:**
I've just started using this variant of ScanTailor (awesome work!) and I haven't done extensive testing to determine if this is a regression and, if so, when it occurred. Would be happy to test if needed.

![testpic](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/55459980/ffb955a8-2edd-4cea-a20e-5bbd8ce79e55)

**Comment by zvezdochiot** [comment] 2024-05-06 19:38
Hi, @fusefib .

In Linux, the one you described cannot be played either on 2x or 4x.

**Comment by fusefib** [comment] 2024-05-06 19:57
I'll try to prepare a better picture for testing. In any case, it consistently does this for pages that are mostly white and have almost no black, when scaling up. However, pages with enough text always turn out fine. Here is the result for me:
[testpic-scaled.zip](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/files/15225675/testpic-scaled.zip)

2x:
![image](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/55459980/5fcfa1f2-8f0c-4737-91bd-655494f9b95f)
4x:
![image](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/55459980/c89f40a6-5f62-487f-b635-4a6dd2d65ab0)

**Comment by plzombie** [comment] 2024-05-07 15:08
@zvezdochiot Reproduced with Otsu, Dots8, EdgePlus(somehow), BlurDiv, EdgeDiv, Robust
Not reproducible in 0.2023.10.24
Reproducible in 0.2023.10.30 and so on
Looks like some bug introduced in 0.2023.10.30 (for all sizes) and partially fixed in 0.2023.11.19 (for size 1.0).
Also if you change image size manually by 50% and then upscale 2x in ScanTailor - everything is ok, but when you upscale 4x you will got the same result like original image with scale 2x (thin black lines).
So its probably something related to image size.

Also reproducible on 32-bit linux. So maybe should look for long (32bit on windows and 32bit linux, 64bit on 64bit linux) variables
![изображение](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/1690651/d6b98d6e-5145-4aed-991b-fca862a771e9)

I suggest to check https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/commit/aafb67f95a0685535c999ede9fb5f8ed5112beed https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/commit/587683bdda23650fa0d237df6ebe85db434f2a13 and https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/compare/0.2023.11.10...0.2023.11.19#diff-4ddd4b67d244ac7c7864d278c0179f232b36742520daee44b20ec5b80e4f6324R870 (and maybe other code) and replace long with int64_t/uint64_t

**Comment by zvezdochiot** [comment] 2024-05-07 16:38
@plzombie , this could be (?!) an overflow in:
https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/blob/11d943af4b93c44e6b89bf47f90388025009e30f/src/imageproc/Binarize.cpp#L197
but the type is specified independent of the bit depth (!).

**Comment by plzombie** [comment] 2024-05-07 20:02
@fusefib Could you try this build?
[staging.zip](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/files/15240298/staging.zip)
[scantailor-experimental-0.2024.05.05-X86-64-Qt6-install.zip](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/files/15240305/scantailor-experimental-0.2024.05.05-X86-64-Qt6-install.zip)

**Comment by fusefib** [comment] 2024-05-08 00:25
Confirmed it works properly now with both zips. Thanks to both of you for the fix!

**Closed** 2024-05-10 11:45 UTC
